### ISSUE TITLE
Report of on-site visit of 20-24/04/2015 to Sheffield

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-support#20]
This is a list of things deserving attention/improvement which we spotted while working with **iCubSheffield01** during the [WYSIWYD](https://github.com/robotology/wysiwyd) integration week held in Sheffield from 20th to 24th of April 2015.

##### Mechanics
- [x] During `ARE` fingers calibration, the left thumb did not behave as expected, while the right thumb did calibrate nicely. The **abduction of the left thumb** (`joint 8`) does not move via the `Gui`, whereas by manually rotating the corresponding screw we managed to make it move. See https://github.com/robotology/icub-support/issues/37. **`Endorsed`**.
- [ ] The **right arm collides with the torso cover** during the first calibration. Apparently, this might be due to a tiny deformation of the cover of the torso in the correspondence of the collision.

##### Software
- [x] `robotInterface` **never run after the first motor start-up**. No matter how long we waited, some boards were not being heard of. Further, we had the same problem after a **fault button** event followed by `robotInterface` shutdown. In both the above situations, a second motor power-cycle made `robotInterface` start correctly. See https://github.com/robotology/icub-support/issues/36. **`Endorsed`**.
- [x] Frequent **HW faults** have been triggered throughout the week, in the neck and in the wrist.
- [x] The **`ARE` kinesthetic teaching** did fail. The teaching went on in admittance mode and, looking into the code, this happens when the function [`setTorque()`](https://github.com/robotology/icub-main/blob/master/src/modules/actionsRenderingEngine/src/MotorThread.cpp#L144) returns `false`. We tested it only once, but it's somehow weird that the admittance control took over the torque mode. **[`Clarified`](https://github.com/robotology/icub-support/issues/20#issuecomment-96977201)**.
- [x] **Reaching accuracy is low**: see robotology/icub-main/issues/140. **`Endorsed`**.
- [x] There's the need for updating **yarp binaries**: see robotology/wysiwyd/issues/12. **`Endorsed`**.

##### System configuration
The **icubsrv** laptop has been shipped back with the following wrong settings:

- [x] The xml file used to launch the **calibrated cameras** was not the updated version; as result, the left and right image streams were swapped. This was quite a nasty bug to find, causing lots of problem with stereo vision. **`Fixed`**.
- [x] Somehow, there were two **bash files** devoted to contain iCub related env variables: `.bash_iCubrc` and `.bashrc_iCub`, with mixed configuration. The standard file must be the former, while `.bashrc` was pointing to the latter, messing up the overall system.
**`Fixed`**.

##### Good news
That's the sore points over, now the good news:

- Thanks to the **new pronosupination**, we have been experiencing an improved matching between the kinematic predictions and the stereo-vision observations in the `depth2kin` experiment.
- We managed to successfully integrate the **stereo-vision** and the **[IOL](https://github.com/robotology/iol) object-recognition** into the `wysiwyd` system!

/cc @lukeboorman @davidetome @super-ste @marcoaccame @randaz81 @lornat75

**Comment by lornat75** [comment]
@mbrunettini @davidetome: check the issue with the configuration of the laptop:

-> Somehow, there were two bash files devoted to contain iCub related env variables: .bash_iCubrc and .bashrc_iCub, with mixed configuration. The standard file must be the former, while .bashrc was pointing to the latter, messing up the overall system.

Just to make sure we do not end up with the same problem in the future.

**Comment by pattacini** [comment]
@randaz81 torque mode for `iCubSheffield01` was purposely disabled, hence `ARE` kinesthetic teaching was clearly not available.

**Comment by lukeboorman** [comment]
We are getting more frequent HW faults on neck joint 0 and I assume this then puts joint 1 into idle...

After startup (viewed with robotMotorGui) and during testing using the ball demo. I can send the robotInterface log file.

Could this be hardware?

**Comment by mbrunettini** [comment]
Hi,
the installation instructions here:
http://wiki.icub.org/wiki/Generic_iCub_machine_installation_instructions
reports only the correct .bashrc_iCub file, as Lorenzo told.
@davidetome : do you confirm you followed the above instructions? In case you’re using an HD image, can you chack it?

Thanks

Matteo
